#ifndef __CODI_ERROR_H__
#define __CODI_ERROR_H__

#define CODIERR_NOERROR						0
#define CODIERR_INVALID_DEVICE				-1
#define CODIERR_DEVICE_BUSY					-2
#define CODIERR_DEVICE_INUSE				-3
#define CODIERR_MEMORY_ERROR				-4

#define CODIERR_INVALID_HANDLE				-5
#define CODIERR_INVALID_BUFFER				-6
#define CODIERR_INVALID_LENGTH				-7
#define CODIERR_INVALID_TIMEOUT				-8

#define CODIERR_ALREADY_INITIALIZED			-9
#define CODIERR_NOT_INITIALIZED				-10
#define CODIERR_INVALID_ID					-11
#define CODIERR_NOT_REGISTERED				-12
#define CODIERR_NOT_STARTED					-13
#define CODIERR_ALREADY_STARTED				-14
#define CODIERR_INVALID_INTERFACE			-15

#define CODIERR_DEVICE_ERROR				-16
#define CODIERR_OUT_OF_BINDING				-17
#define CODIERR_INUSE_ENDDEVICE				-18
#define CODIERR_INVALID_KEY					-19
#define CODIERR_REPLY_TIMEOUT				-20
#define CODIERR_INVALID_PARAM				-21
#define CODIERR_COMMAND_ERROR				-22
#define CODIERR_UNKNOWN_ERROR				-23
#define CODIERR_NOT_CONNECTED				-24
#define CODIERR_COORDINATOR_NOT_READY		-25
#define CODIERR_INVALID_OPTION				-26
#define CODIERR_INVALID_METHOD				-27

#define CODIERR_INVALID_PARENT				-50
#define CODIERR_PARENT_BINDING_ERROR		-51
#define CODIERR_SET_CHILD_ERROR				-52	

#define CODIERR_PROGRESS					-100

#define CODIERR_SERIAL_TIMEOUT				-200	/* Coordinator Information Error */
#define CODIERR_SERIAL_ERROR				-201
#define CODIERR_FRAME_CONTROL_ERROR			-202
#define CODIERR_REQUEST_ERROR				-203
#define CODIERR_FRAME_TYPE_ERROR			-204
#define CODIERR_CRC16_ERROR					-205

#define CODIERR_NOT_SUPPORTED				-230	/* Coordinator Command Error */
#define CODIERR_INVALID_DATA				-231
#define CODIERR_NO_NETWORK_ERROR			-232
#define CODIERR_FORM_NETWORK_ERROR			-233
#define CODIERR_LEAVE_NETWORK_ERROR			-234
#define CODIERR_BIND_ADDRESS_DUPLICATION	-235
#define CODIERR_FULL_BINDING_INDEX			-236
#define CODIERR_EUI64_FOUND_FAIL_ERROR		-237
#define CODIERR_SET_BINDING_ERROR			-238
#define CODIERR_DELETE_BINDING_ERROR		-239
#define CODIERR_BINDING_IS_ACTIVE_ERROR		-240
#define CODIERR_GET_BINDING_ERROR           -241
#define CODIERR_GET_NEIGHBOR_ERROR          -242
#define CODIERR_KEY_TABLE_DUPLICATION       -243
#define CODIERR_NULL_KEY_INDEX              -244
#define CODIERR_SET_KEY_ERROR               -245
#define CODIERR_KEY_FOUND_FAIL_ERROR        -246
#define CODIERR_DEL_KEY_ERROR               -247
#define CODIERR_ADD_ERROR					-248
#define CODIERR_DEL_ERROR					-249
#define CODIERR_ADD_DUPLICATE_ERROR			-250

#define CODIERR_SEND_DATA_ERROR				-260	/* End Device Data Error */
#define CODIERR_PAYLOAD_LENGTH_ERROR		-261
#define CODIERR_DELIVERY_ERROR				-262
#define CODIERR_BINDING_ERROR				-263

#endif	/* __CODI_ERROR_H__ */
