#ifndef __DLMS_RESULT_H__
#define __DLMS_RESULT_H__

#define DLMSRES_OK							0
#define DLMSRES_HARDWARE_FAULT				1
#define DLMSRES_TEMPORARY_FAILURE			2
#define DLMSRES_READ_WRITE_DENIED			3
#define DLMSRES_OBJECT_UNDEFINED			4
#define DLMSRES_OBJECT_CLASS_INCONSISTENT	9
#define DLMSRES_OBJECT_UNAVAILABLE			11
#define DLMSRES_TYPE_UNMATCHED				12
#define DLMSRES_SCOPE_OF_ACCESS_VIOLATED	13
#define DLMSRES_DATA_BLOCK_UNAVAILABLE		14
#define DLMSRES_LONG_ACTION_ABORTED			15
#define DLMSRES_NO_LONG_ACTION_IN_PROGRESS	16
#define DLMSRES_OTHER_REASON				250

#endif	// __DLMS_RESULT_H__
