#ifndef __DLMS_CLASSES_H__
#define __DLMS_CLASSES_H__

#define DLMS_CLASS_DATA						1
#define DLMS_CLASS_RESERVED					2
#define DLMS_CLASS_REGISTER					3
#define DLMS_CLASS_EXTENDED_REGISTER		4
#define DLMS_CLASS_DEMAND_REGISTER			5
#define DLMS_CLASS_REGISTER_ACTIVATION		6
#define DLMS_CLASS_PROFILE_GENERIC			7
#define DLMS_CLASS_CLOCK					8
#define DLMS_CLASS_SCRIPT_TABLE				9
#define DLMS_CLASS_SCHEDULE					10
#define DLMS_CLASS_SPECIAL_DAYS_TABLE		11
#define DLMS_CLASS_ASSOCIATION_SN			12
#define DLMS_CLASS_ASSOCIATION_LN			15
#define DLMS_CLASS_SAP_ASSIGNMENT			17
#define DLMS_CLASS_IEC_LOCAL_PORT_SETUP		19
#define DLMS_CLASS_ACTIVITY_CALENDAR		20
#define DLMS_CLASS_REGISTER_MONITOR			21
#define DLMS_CLASS_SINGLE_ACTION_SCHEDULE	22
#define DLMS_CLASS_IEC_HDLC_SETUP			23
#define DLMS_CLASS_IEC_TWISTED_PAIR1		24				// (1) Setup - EURIDIS
#define DLMS_CLASS_IEC_TWISTED_PAIR2		25				// (2) Setup - CEN - Mbus
#define DLMS_CLASS_UTILITY_TABLES			26
#define DLMS_CLASS_PSTN_MODEM_CONFIGURATION	27
#define DLMS_CLASS_PSTN_AUTO_ANSWER			28
#define DLMS_CLASS_PSTN_AUTO_DIAL			29

#endif	// __DLMS_CLASSES_H__

