#ifndef __ANSI_ERROR_H__
#define __ANSI_ERROR_H__

#define ANSIERR_NOERROR						0		// No error

#define ANSIERR_INVALID_PARAM				-50
#define ANSIERR_INVALID_SESSION				-51
#define ANSIERR_INVALID_HANDLE				-52
#define ANSIERR_INVALID_ADDRESS				-53
#define ANSIERR_INVALID_TIMEOUT				-57
#define ANSIERR_INVALID_ACCESS				-58
#define ANSIERR_INVALID_DATA				-59
#define ANSIERR_INVALID_ACTION				-60
#define ANSIERR_INVALID_STRING				-62
#define ANSIERR_INVALID_LENGTH				-63
#define ANSIERR_INVALID_BUFFER				-64

#define ANSIERR_FRAME_ERROR                 -70

#define ANSIERR_CANNOT_CONNECT				-100
#define ANSIERR_REPLY_TIMEOUT				-101
#define ANSIERR_NOT_INITIALIZED				-102

#define ANSIERR_SYSTEM_ERROR				-200
#define ANSIERR_MEMORY_ERROR				-201

#endif	// __ANSI_ERROR_H__
